### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by johnfelipe** [jawMeister/portfolio-analysis-app#1]
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
	Traceback:
	File "/usr/local/lib/python3.8/dist-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
		exec(code, module.__dict__)
	File "/root/portfolio-analysis-app/app.py", line 206, in <module>
		app()
	File "/root/portfolio-analysis-app/app.py", line 192, in app
		financials.display_financials_analysis(st.session_state.portfolio_summary)
	File "/root/portfolio-analysis-app/src/financials/display.py", line 114, in display_financials_analysis
		if int(os.getenv('GPT_TOKEN_LIMIT')) <= 8000:

i run all this steps

	apt update
	apt upgrade
	shutdown -r now
	
	sudo su
	cd
	apt install python3-pip
	pip install streamlit
	pip install streamlit --upgrade
	pip install Jinja2==3
	git clone https://github.com/jawMeister/portfolio-analysis-app

	cd portfolio-analysis-app/
	pip install -r requirements.txt

	bash run-streamlit.sh

how solved?

**Comment by johnfelipe** [comment]
i update all and do this:

	openai migrate

	(env) root@template:~/portfolio-analysis-app# openai migrate
	Retrieving Grit CLI metadata from https://api.keygen.sh/v1/accounts/custodian-dev/artifacts/marzano-linux-x64
	Your working tree currently has untracked changes and Grit will rewrite files in place. Do you want to proceed? [y/N] y

https://gist.github.com/johnfelipe/be7911705a652a9e1d80ca1ca604363b

and in another console


	Traceback (most recent call last):
	  File "/root/portfolio-analysis-app/src/portfolio/display.py", line 174, in display_selected_portfolio
		response = interpret.openai_interpret_portfolio_summary(portfolio_summary)
	  File "/root/portfolio-analysis-app/src/portfolio/interpret.py", line 30, in openai_interpret_portfolio_summary
		chat_completion = openai.ChatCompletion.create(model="gpt-3.5-turbo", messages=[{"role": "user", "content": question}])
	  File "/root/portfolio-analysis-app/env/lib/python3.10/site-packages/openai/lib/_old_api.py", line 39, in __call__
		raise APIRemovedInV1(symbol=self._symbol)
	openai.lib._old_api.APIRemovedInV1:

	You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

	You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface.

	Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

	A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742

	/root/portfolio-analysis-app/env/lib/python3.10/site-packages/pypfopt/expected_returns.py:56: FutureWarning:

	The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.

	/root/portfolio-analysis-app/env/lib/python3.10/site-packages/pypfopt/expected_returns.py:56: FutureWarning:

	The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.

	2023-12-11 15:48:24.841 Uncaught app exception
	Traceback (most recent call last):
	  File "/root/portfolio-analysis-app/env/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
		exec(code, module.__dict__)
	  File "/root/portfolio-analysis-app/app.py", line 206, in <module>
		app()
	  File "/root/portfolio-analysis-app/app.py", line 192, in app
		financials.display_financials_analysis(st.session_state.portfolio_summary)
	  File "/root/portfolio-analysis-app/src/financials/display.py", line 114, in display_financials_analysis
		if int(os.getenv('GPT_TOKEN_LIMIT')) <= 8000:
	TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
	2023-12-11 15:50:20.676 Uncaught app exception
	Traceback (most recent call last):
	  File "/root/portfolio-analysis-app/env/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
		exec(code, module.__dict__)
	  File "/root/portfolio-analysis-app/app.py", line 17, in <module>
		from src.portfolio import display as portfolio
	  File "/root/portfolio-analysis-app/src/portfolio/__init__.py", line 1, in <module>
		from .display import display_selected_portfolio
	  File "/root/portfolio-analysis-app/src/portfolio/display.py", line 18, in <module>
		import src.portfolio.interpret as interpret
	  File "/root/portfolio-analysis-app/src/portfolio/interpret.py", line 4, in <module>
		client = OpenAI(api_key=config.get_api_key('openai'))
	NameError: name 'config' is not defined
	2023-12-11 15:50:20.962 Uncaught app exception
	Traceback (most recent call last):
	  File "/root/portfolio-analysis-app/env/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
		exec(code, module.__dict__)
	  File "/root/portfolio-analysis-app/app.py", line 17, in <module>
		from src.portfolio import display as portfolio
	  File "/root/portfolio-analysis-app/src/portfolio/__init__.py", line 1, in <module>
		from .display import display_selected_portfolio
	  File "/root/portfolio-analysis-app/src/portfolio/display.py", line 18, in <module>
		import src.portfolio.interpret as interpret
	  File "/root/portfolio-analysis-app/src/portfolio/interpret.py", line 4, in <module>
		client = OpenAI(api_key=config.get_api_key('openai'))
	NameError: name 'config' is not defined
	2023-12-11 15:50:21.623 Uncaught app exception
	Traceback (most recent call last):
	  File "/root/portfolio-analysis-app/env/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
		exec(code, module.__dict__)
	  File "/root/portfolio-analysis-app/app.py", line 17, in <module>
		from src.portfolio import display as portfolio
	  File "/root/portfolio-analysis-app/src/portfolio/__init__.py", line 1, in <module>
		from .display import display_selected_portfolio
	  File "/root/portfolio-analysis-app/src/portfolio/display.py", line 18, in <module>
		import src.portfolio.interpret as interpret
	  File "/root/portfolio-analysis-app/src/portfolio/interpret.py", line 4, in <module>
		client = OpenAI(api_key=config.get_api_key('openai'))
	NameError: name 'config' is not defined
	2023-12-11 15:50:23.026 Uncaught app exception
	Traceback (most recent call last):
	  File "/root/portfolio-analysis-app/env/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
		exec(code, module.__dict__)
	  File "/root/portfolio-analysis-app/app.py", line 17, in <module>
		from src.portfolio import display as portfolio
	  File "/root/portfolio-analysis-app/src/portfolio/__init__.py", line 1, in <module>
		from .display import display_selected_portfolio
	  File "/root/portfolio-analysis-app/src/portfolio/display.py", line 18, in <module>
		import src.portfolio.interpret as interpret
	  File "/root/portfolio-analysis-app/src/portfolio/interpret.py", line 4, in <module>
		client = OpenAI(api_key=config.get_api_key('openai'))
	NameError: name 'config' is not defined
	2023-12-11 15:52:42.363 Uncaught app exception
	Traceback (most recent call last):
	  File "/root/portfolio-analysis-app/env/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
		exec(code, module.__dict__)
	  File "/root/portfolio-analysis-app/app.py", line 17, in <module>
		from src.portfolio import display as portfolio
	  File "/root/portfolio-analysis-app/src/portfolio/__init__.py", line 1, in <module>
		from .display import display_selected_portfolio
	  File "/root/portfolio-analysis-app/src/portfolio/display.py", line 18, in <module>
		import src.portfolio.interpret as interpret
	  File "/root/portfolio-analysis-app/src/portfolio/interpret.py", line 4, in <module>
		client = OpenAI(api_key=config.get_api_key('openai'))
	NameError: name 'config' is not defined
